ERRNO_TOKEN_ABSENT = 1
ERRNO_TOKEN_OUTDATED = 2
ERRNO_TOKEN_INVALID = 3
ERRNO_INVALID_DEVICE = 10
ERRNO_INVALID_PASSWORD = 11
ERRNO_INVALID_KEY = 12
ERRNO_INTERNAL_UNKNOWN = 40
ERRNO_FIELDS_ABSENT = 50